title: "Krishnakumar's GitHub Page"
description: "Showcasing my professional profile and experiences."
baseurl: ""
url: "https://yourusername.github.io/krishnakumar-github-page"
theme: "minimal"
author:
  name: "Krishnakumar P"
  email: "your-email@example.com"
social:
  linkedin: "https://www.linkedin.com/in/krishnakumar-p-1a1827114/"
  github: "https://github.com/yourusername"